#!/usr/bin/env python3
"""agent-foundry: scaffold working agent projects from the command line.

Stdlib only. Commands:
  agent-foundry new <name> [--dir ./] [--force]
  agent-foundry validate <project-dir>
"""

import argparse
import json
import os
import re
import sys

__version__ = "0.1.0"

# Names must not start or end with a hyphen: a leading hyphen collides with
# CLI flags on later invocations, and both ends produce awkward directory names.
NAME_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$")

REQUIRED_MANIFEST_KEYS = ("name", "version", "description", "entrypoint", "skills")


# ---------------------------------------------------------------- templates

def _manifest_template(name):
    return json.dumps(
        {
            "name": name,
            "publisher": "MBM AI Solutions",
            "version": "0.1.0",
            "description": "Scaffolded agent project '%s' generated by agent-foundry." % name,
            "entrypoint": "agent.py",
            "skills": ["agent-foundry"],
            "capabilities": ["hello-task"],
            "security": {
                "external_actions": "human_review_required",
                "customer_data": "authorized_data_only",
            },
            "status": "scaffold",
            "note": "This manifest does not claim a connected production integration. "
                    "Deployment and provider credentials are platform-specific.",
        },
        indent=2,
    ) + "\n"


TITLE = lambda name: name.replace("-", " ").title()

def _skill_template(name):
    return (
        "---\n"
        "name: %s\n"
        "description: Hello-agent scaffold generated by agent-foundry. "
        "Responds to a 'hello' task by reading its own manifest.\n"
        "---\n"
        "\n"
        "# %s\n"
        "\n"
        "Use when the user wants a minimal working agent that greets by name "
        "and proves its manifest wiring.\n"
        "\n"
        "## Workflow\n"
        "\n"
        "1. Load manifest.json from the project directory.\n"
        "2. Read the task string passed to the entrypoint.\n"
        "3. For task `hello`, return a greeting that includes the manifest name.\n"
        "4. For any other task, echo the task together with the manifest name.\n"
        "5. Never invent customer data, permissions, credentials, tool connectivity, "
        "or measured outcomes.\n"
        "\n"
        "## Output\n"
        "\n"
        "Return:\n"
        "- Greeting line containing the agent name from the manifest\n"
        "- The task string that was handled\n"
    ) % (name, TITLE(name))


def _agent_template(name):
    return '''#!/usr/bin/env python3
"""%s: hello-agent entrypoint generated by agent-foundry.

Stdlib only. Reads its own manifest.json so the greeting proves the
manifest wiring works:

    python agent.py --task "hello"
"""

import argparse
import json
import os
import sys

MANIFEST_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "manifest.json")


def load_manifest(path=MANIFEST_PATH):
    """Load and return the project's manifest.json as a dict."""
    with open(path, "r", encoding="utf-8-sig") as fh:
        data = json.load(fh)
    if not isinstance(data, dict):
        raise ValueError("manifest.json must contain a JSON object")
    return data


def handle_task(task, manifest):
    """Return the response string for a task. Pure function; easy to test."""
    name = manifest.get("name", "agent")
    if task == "hello":
        return "hello from %%s: manifest wiring OK" %% name
    return "%%s received task: %%s" %% (name, task)


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="agent.py", description="Hello-agent entrypoint for %s."
    )
    parser.add_argument("--task", default="hello", help="Task string to handle.")
    args = parser.parse_args(argv)
    try:
        manifest = load_manifest()
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print("error: cannot load manifest.json: %%s" %% exc, file=sys.stderr)
        return 1
    print(handle_task(args.task, manifest))
    return 0


if __name__ == "__main__":
    sys.exit(main())
''' % (TITLE(name), TITLE(name))


def _scaffold_test_template(name):
    return '''"""Tests for the scaffolded %s agent. Run: python -m unittest discover -s tests"""
import json
import os
import subprocess
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import agent


class TestHelloAgent(unittest.TestCase):
    def test_manifest_loads(self):
        manifest = agent.load_manifest()
        self.assertEqual(manifest["name"], "%s")

    def test_hello_mentions_manifest_name(self):
        manifest = agent.load_manifest()
        out = agent.handle_task("hello", manifest)
        self.assertIn(manifest["name"], out)
        self.assertTrue(out.lower().startswith("hello"))

    def test_other_task_echoes(self):
        manifest = agent.load_manifest()
        out = agent.handle_task("ping", manifest)
        self.assertIn("ping", out)
        self.assertIn(manifest["name"], out)

    def test_cli_hello(self):
        result = subprocess.run(
            [sys.executable, os.path.join(ROOT, "agent.py"), "--task", "hello"],
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 0)
        manifest = agent.load_manifest()
        self.assertIn(manifest["name"], result.stdout)


if __name__ == "__main__":
    unittest.main()
''' % (name, name)


def _readme_template(name):
    return (
        "# %s\n"
        "\n"
        "Minimal agent project scaffolded by agent-foundry.\n"
        "\n"
        "## What it does\n"
        "\n"
        "Reads `manifest.json` and responds to a task string. `hello` returns a\n"
        "greeting that includes the agent name from the manifest, proving the\n"
        "manifest wiring works. Any other task string is echoed back.\n"
        "\n"
        "## Run\n"
        "\n"
        "```sh\n"
        "python agent.py --task \"hello\"\n"
        "```\n"
        "\n"
        "## Test\n"
        "\n"
        "```sh\n"
        "python -m unittest discover -s tests\n"
        "```\n"
        "\n"
        "## Files\n"
        "\n"
        "- `manifest.json` — agent manifest (name, version, entrypoint, skills)\n"
        "- `SKILL.md` — skill description for this agent\n"
        "- `agent.py` — runnable entrypoint\n"
        "- `tests/` — unit tests\n"
    ) % TITLE(name)


# ---------------------------------------------------------------- commands

def cmd_new(args):
    name = args.name
    if not NAME_RE.match(name):
        print(
            "error: invalid agent name %r: use lowercase letters, numbers, and "
            "hyphens only, and do not start or end the name with a hyphen"
            % name,
            file=sys.stderr,
        )
        return 2
    base = os.path.abspath(os.path.expanduser(args.dir))
    if os.path.exists(base) and not os.path.isdir(base):
        print("error: --dir is not a directory: %s" % base, file=sys.stderr)
        return 2
    target = os.path.join(base, name)
    if os.path.exists(target) and not os.path.isdir(target):
        print(
            "error: target %r exists and is not a directory; choose another name"
            % target,
            file=sys.stderr,
        )
        return 2
    if os.path.isdir(target) and os.listdir(target) and not args.force:
        print(
            "error: directory %r is not empty; pass --force to overwrite" % target,
            file=sys.stderr,
        )
        return 2
    try:
        os.makedirs(target, exist_ok=True)
    except OSError as exc:
        print(
            "error: cannot create directory %r: %s" % (target, exc), file=sys.stderr
        )
        return 1
    files = {
        "manifest.json": _manifest_template(name),
        "SKILL.md": _skill_template(name),
        "agent.py": _agent_template(name),
        os.path.join("tests", "test_agent.py"): _scaffold_test_template(name),
        "README.md": _readme_template(name),
    }
    try:
        for relpath, content in files.items():
            full = os.path.join(target, relpath)
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w", encoding="utf-8") as fh:
                fh.write(content)
    except OSError as exc:
        print("error: failed to write scaffold files: %s" % exc, file=sys.stderr)
        return 1
    print("scaffolded agent %r at %s" % (name, target))
    return 0


def cmd_validate(args):
    project = os.path.abspath(args.project_dir)
    problems = []
    if not os.path.isdir(project):
        print("error: not a directory: %s" % project, file=sys.stderr)
        return 1
    manifest_path = os.path.join(project, "manifest.json")
    if not os.path.isfile(manifest_path):
        problems.append("missing manifest.json")
        manifest = None
    else:
        try:
            with open(manifest_path, "r", encoding="utf-8-sig") as fh:
                manifest = json.load(fh)
        except (OSError, json.JSONDecodeError) as exc:
            problems.append("manifest.json does not parse: %s" % exc)
            manifest = None
        if manifest is not None:
            if not isinstance(manifest, dict):
                problems.append("manifest.json must contain a JSON object")
                manifest = None
            else:
                for key in REQUIRED_MANIFEST_KEYS:
                    if key not in manifest:
                        problems.append("manifest.json missing required key: %s" % key)
                for key in ("name", "version", "description"):
                    if key in manifest and not isinstance(manifest[key], str):
                        problems.append("manifest.json %r must be a string" % key)
                if "skills" in manifest:
                    skills = manifest["skills"]
                    if not isinstance(skills, list):
                        problems.append("manifest.json 'skills' must be a list")
                    elif not all(isinstance(s, str) for s in skills):
                        problems.append(
                            "manifest.json 'skills' must be a list of strings"
                        )
                entrypoint = manifest.get("entrypoint")
                if "entrypoint" in manifest and not isinstance(entrypoint, str):
                    problems.append("manifest.json 'entrypoint' must be a string")
                elif isinstance(entrypoint, str):
                    # The entrypoint must live inside the project: absolute
                    # paths and ".." segments are rejected, not resolved.
                    parts = entrypoint.replace("\\", "/").split("/")
                    if os.path.isabs(entrypoint) or ".." in parts:
                        problems.append(
                            "entrypoint must be a relative path inside the "
                            "project: %s" % entrypoint
                        )
                    else:
                        entry_path = os.path.join(project, entrypoint)
                        if not os.path.isfile(entry_path):
                            problems.append("entrypoint not found: %s" % entrypoint)
    skill_path = os.path.join(project, "SKILL.md")
    if not os.path.isfile(skill_path):
        problems.append("missing SKILL.md")
    if problems:
        print("invalid agent project: %s" % project)
        for p in problems:
            print("  - %s" % p)
        return 1
    print("valid agent project: %s" % project)
    return 0


def build_parser():
    parser = argparse.ArgumentParser(
        prog="agent-foundry",
        description=__doc__,
        epilog=(
            "Examples:\n"
            "  agent-foundry new my-agent --dir ./projects\n"
            "  agent-foundry validate ./projects/my-agent\n"
            "Exit codes: 0 success, 1 validation/IO failure, 2 usage error."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--version", action="version", version="agent-foundry " + __version__
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_new = sub.add_parser("new", help="Scaffold a new agent project.")
    p_new.add_argument("name", help="Agent name: lowercase letters, numbers, hyphens only.")
    p_new.add_argument("--dir", default=".", help="Parent directory (default: current dir).")
    p_new.add_argument("--force", action="store_true", help="Overwrite a non-empty directory.")
    p_new.set_defaults(func=cmd_new)

    p_val = sub.add_parser("validate", help="Validate a scaffolded agent project.")
    p_val.add_argument("project_dir", help="Path to the agent project directory.")
    p_val.set_defaults(func=cmd_validate)

    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
